eureka:
  client:
#    表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: false
#    表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: false
#设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8000
spring:
  application:
    name: spring-cloud-eureka
