server:
  port: 8888
spring:
  application:
    name: gateway-service-zuul
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
#此处配置可以调用网页
#zuul:
#  routes:
#    baidu:
#      path: /it/**
#      url: http://www.ityouknow.com/
zuul:
  routes:
    api-a:
      path: /client/**
      serviceId: spring-cloud-client
  FormBodyWrapperFilter:
    pre:
      disable: true
#是否开启重试功能
  retryable: true
ribbon:
  #对当前服务的重试次数
  MaxAutoRetries: 2
  #切换相同Server的次数
  MaxAutoRetriesNextServer: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
