server:
  port: 8502
spring:
  application:
    name: spring-cloud-consul-server
  cloud:
    consul:
      discovery:
        serviceName: service-producer
      host: 127.0.0.1
      port: 8500
