eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 9001
spring:
  application:
    name: spring-cloud-client
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/haiyu
    username: root
    password: root
    # druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
# 启用熔断器 这儿idea 有提示不存在但是仍然要写
feign:
  hystrix:
    enabled: true
mybatis:
  # 映射文件所在路径
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      haiyu:
        client: DEBUG

